library('testthat')
library('assertthat')
standardize <- function(x, na.rm = FALSE) {
  z <- (x - mean(x, na.rm = na.rm)) / sd(x, na.rm = na.rm)
  return(z)
}
a <- c(2,4,7,8,9)
z<-standardize(a)
z
mean(z)
sd(z)
y<-c(1,2,3,4,NA)
standardize(y)
standardize(y, na.rm=TRUE)
alog <- c(TRUE, FALSE, FALSE, TRUE)
standardize(alog)
x<-c(1,2,3)
z<-(x-mean(x))/sd(x)
expect_equal(standardize(x),z)
expect_equal(standardize(x),x)
expect_length(standardize(x), length(x))
expect_type(standardize(x), 'double')
expect_length(standardize(x), 2)
expect_type(standardize(x), 'character')
y<-c(1,2,NA)
z1<-(y - mean(y, na.rm=FALSE))/ sd(y, na.rm=FALSE)
z2<-(y - mean(y, na.rm=TRUE))/ sd(y, na.rm= TRUE)
expect_equal(standardize(y), z1)
expect_lengths(standardize(y), length(y))
expect_length(standardize(y), length(y))
library(testthat)
test_file(test.R)
test_file(test.R)
test_file('test.R')
